# Generated by Django 5.1.3 on 2024-11-18 06:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Personaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('poder', models.IntegerField(default=0)),
                ('nivel', models.IntegerField(default=1)),
                ('experiencia', models.IntegerField(default=0)),
                ('daño_minimo', models.IntegerField(default=1)),
                ('daño_maximo', models.IntegerField(default=1000)),
                ('puntos_de_vida', models.IntegerField(default=100)),
                ('armadura', models.IntegerField(default=10)),
                ('energia', models.IntegerField(default=12)),
                ('fuerza', models.IntegerField(default=10)),
                ('dextiridad', models.IntegerField(default=10)),
                ('agilidad', models.IntegerField(default=10)),
                ('vida', models.IntegerField(default=100)),
                ('inteligencia', models.IntegerField(default=10)),
                ('oro', models.IntegerField(default=100)),
                ('costo_mejora_fuerza', models.IntegerField(default=10)),
                ('costo_mejora_dextiridad', models.IntegerField(default=10)),
                ('costo_mejora_agilidad', models.IntegerField(default=8)),
                ('costo_mejora_vida', models.IntegerField(default=5)),
                ('costo_mejora_inteligencia', models.IntegerField(default=6)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Objeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('tipo', models.CharField(max_length=50)),
                ('valor_subasta', models.IntegerField(blank=True, null=True)),
                ('costo_oro', models.IntegerField(default=10)),
                ('daño_min', models.IntegerField(default=0)),
                ('daño_max', models.IntegerField(default=0)),
                ('armadura', models.IntegerField(default=0)),
                ('efecto', models.CharField(blank=True, max_length=100, null=True)),
                ('imagen', models.ImageField(default='default.png', upload_to='objetos/')),
            ],
        ),
        migrations.CreateModel(
            name='Raza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('bonificacion_fuerza', models.IntegerField(default=0)),
                ('bonificacion_dextiridad', models.IntegerField(default=0)),
                ('bonificacion_agilidad', models.IntegerField(default=0)),
                ('bonificacion_vida', models.IntegerField(default=0)),
                ('bonificacion_inteligencia', models.IntegerField(default=0)),
                ('imagen', models.ImageField(default='default.png', upload_to='razas/')),
            ],
        ),
        migrations.CreateModel(
            name='Vendedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Heroe',
            fields=[
                ('personaje_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Characters.personaje')),
                ('ranking_global', models.IntegerField(default=0, editable=False)),
            ],
            bases=('Characters.personaje',),
        ),
        migrations.AddField(
            model_name='personaje',
            name='anillo_principal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Anillo_principal', to='Characters.objeto'),
        ),
        migrations.AddField(
            model_name='personaje',
            name='anillo_secundario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Anillo_secundario', to='Characters.objeto'),
        ),
        migrations.AddField(
            model_name='personaje',
            name='botas',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Botas', to='Characters.objeto'),
        ),
        migrations.AddField(
            model_name='personaje',
            name='cabeza',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Cabeza', to='Characters.objeto'),
        ),
        migrations.AddField(
            model_name='personaje',
            name='cuello',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Collar', to='Characters.objeto'),
        ),
        migrations.AddField(
            model_name='personaje',
            name='guantes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Guantes', to='Characters.objeto'),
        ),
        migrations.AddField(
            model_name='personaje',
            name='mano_principal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Mano_principal', to='Characters.objeto'),
        ),
        migrations.AddField(
            model_name='personaje',
            name='mano_secundaria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Mano_secundaria', to='Characters.objeto'),
        ),
        migrations.AddField(
            model_name='personaje',
            name='piernas',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Piernas', to='Characters.objeto'),
        ),
        migrations.AddField(
            model_name='personaje',
            name='torso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Torso', to='Characters.objeto'),
        ),
        migrations.AddField(
            model_name='personaje',
            name='raza',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Characters.raza'),
        ),
        migrations.AddField(
            model_name='objeto',
            name='vendedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Characters.vendedor'),
        ),
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objeto', models.ManyToManyField(blank=True, to='Characters.objeto')),
                ('heroe', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Characters.heroe')),
            ],
        ),
    ]
