# Generated by Django 5.1.3 on 2024-11-18 14:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Characters', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enemigo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('puntos_vida', models.IntegerField(default=100)),
                ('daño_minimo', models.IntegerField(default=10)),
                ('daño_maximo', models.IntegerField(default=20)),
                ('armadura', models.IntegerField(default=5)),
            ],
        ),
        migrations.CreateModel(
            name='Mapa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='heroe',
            name='nivel_actual',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='heroe',
            name='progreso_nivel_mapa',
            field=models.IntegerField(default=1),
        ),
        migrations.CreateModel(
            name='Combate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('resultado', models.CharField(max_length=100)),
                ('heroe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Characters.heroe')),
                ('enemigo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Characters.enemigo')),
            ],
        ),
        migrations.AddField(
            model_name='heroe',
            name='mapa_actual',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Characters.mapa'),
        ),
    ]
