# Generated by Django 5.1.3 on 2024-11-18 14:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Characters', '0002_enemigo_mapa_heroe_nivel_actual_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nivel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
                ('jefe', models.BooleanField(default=False)),
                ('enemigos', models.ManyToManyField(to='Characters.enemigo')),
                ('mapa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='niveles', to='Characters.mapa')),
            ],
        ),
    ]
