# Generated by Django 5.1.3 on 2024-11-18 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Characters', '0003_nivel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enemigo',
            old_name='puntos_vida',
            new_name='puntos_de_vida',
        ),
    ]
