# Generated by Django 5.1.3 on 2024-11-18 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Characters', '0005_combate_detalles_rondas'),
    ]

    operations = [
        migrations.AddField(
            model_name='heroe',
            name='vida_actual',
            field=models.IntegerField(default=100),
        ),
    ]
