# Generated by Django 5.1.3 on 2024-11-18 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Characters', '0006_heroe_vida_actual'),
    ]

    operations = [
        migrations.AddField(
            model_name='objeto',
            name='vida_actual',
            field=models.IntegerField(default=0),
        ),
    ]
