# Generated by Django 5.1.3 on 2024-11-18 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Characters', '0007_objeto_vida_actual'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objeto',
            name='armadura',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='objeto',
            name='costo_oro',
            field=models.IntegerField(blank=True, default=10, null=True),
        ),
        migrations.AlterField(
            model_name='objeto',
            name='daño_max',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='objeto',
            name='daño_min',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='objeto',
            name='vida_actual',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
