# Generated by Django 5.1.3 on 2024-11-18 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Characters', '0008_alter_objeto_armadura_alter_objeto_costo_oro_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='objeto',
            name='vida_actual',
        ),
    ]
