# Generated by Django 5.1.3 on 2024-11-18 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Characters', '0009_remove_objeto_vida_actual'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('puntos_recuperacion', models.IntegerField(default=10)),
            ],
        ),
    ]
