# Generated by Django 5.1.3 on 2024-11-18 19:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Characters', '0010_alimento'),
    ]

    operations = [
        migrations.AddField(
            model_name='alimento',
            name='vendedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Characters.vendedor'),
        ),
    ]
