# Generated by Django 5.1.3 on 2024-11-18 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Characters', '0011_alimento_vendedor'),
    ]

    operations = [
        migrations.AddField(
            model_name='alimento',
            name='costo_oro',
            field=models.IntegerField(blank=True, default=10, null=True),
        ),
        migrations.AddField(
            model_name='alimento',
            name='valor_subasta',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
