# Generated by Django 5.1.3 on 2024-11-18 19:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Characters', '0012_alimento_costo_oro_alimento_valor_subasta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alimento',
            name='valor_subasta',
        ),
        migrations.RemoveField(
            model_name='alimento',
            name='vendedor',
        ),
        migrations.RemoveField(
            model_name='inventario',
            name='objeto',
        ),
        migrations.AddField(
            model_name='alimento',
            name='cantidad_disponible',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='alimento',
            name='costo_oro',
            field=models.IntegerField(default=10),
        ),
        migrations.CreateModel(
            name='InventarioAlimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(default=1)),
                ('alimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Characters.alimento')),
                ('inventario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Characters.inventario')),
            ],
        ),
        migrations.AddField(
            model_name='inventario',
            name='alimentos',
            field=models.ManyToManyField(through='Characters.InventarioAlimento', to='Characters.alimento'),
        ),
    ]
