# Generated by Django 5.1.3 on 2024-11-18 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Characters', '0013_remove_alimento_valor_subasta_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventarioalimento',
            name='objeto',
            field=models.ManyToManyField(blank=True, to='Characters.objeto'),
        ),
    ]
