# Generated by Django 5.1.3 on 2024-11-18 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Characters', '0014_inventarioalimento_objeto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventarioalimento',
            name='objeto',
        ),
        migrations.AddField(
            model_name='inventario',
            name='objeto',
            field=models.ManyToManyField(blank=True, to='Characters.objeto'),
        ),
    ]
