# Generated by Django 5.1.3 on 2024-11-19 17:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Characters', '0016_objeto_cantidad_disponible'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventarioalimento',
            name='alimento',
        ),
        migrations.RemoveField(
            model_name='inventario',
            name='alimentos',
        ),
        migrations.RemoveField(
            model_name='inventarioalimento',
            name='inventario',
        ),
        migrations.RemoveField(
            model_name='inventario',
            name='objeto',
        ),
        migrations.RemoveField(
            model_name='objeto',
            name='valor_subasta',
        ),
        migrations.AddField(
            model_name='objeto',
            name='puntos_recuperacion',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.CreateModel(
            name='InventarioItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(default=1)),
                ('inventario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Characters.inventario')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Characters.objeto')),
            ],
        ),
        migrations.AddField(
            model_name='inventario',
            name='items',
            field=models.ManyToManyField(through='Characters.InventarioItem', to='Characters.objeto'),
        ),
        migrations.DeleteModel(
            name='Alimento',
        ),
        migrations.DeleteModel(
            name='InventarioAlimento',
        ),
    ]
