# Generated by Django 5.1.3 on 2024-11-19 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Characters', '0017_remove_inventarioalimento_alimento_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventario',
            old_name='items',
            new_name='objeto',
        ),
    ]
