# Generated by Django 5.1.3 on 2024-11-19 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Characters', '0018_rename_items_inventario_objeto'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='InventarioItem',
            new_name='InventarioObjeto',
        ),
    ]
