# Generated by Django 5.1.3 on 2024-11-19 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Characters', '0019_rename_inventarioitem_inventarioobjeto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventarioobjeto',
            old_name='item',
            new_name='objeto',
        ),
    ]
