# Generated by Django 5.1.3 on 2024-11-19 22:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Characters', '0020_rename_item_inventarioobjeto_objeto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personaje',
            name='raza',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Characters.raza'),
        ),
    ]
