# Generated by Django 5.1.3 on 2024-11-19 22:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Characters', '0021_alter_personaje_raza'),
    ]

    operations = [
        migrations.AddField(
            model_name='personaje',
            name='inventario',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='heroe_inventario', to='Characters.inventario'),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='heroe',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='inventario_heroe', to='Characters.heroe'),
        ),
        migrations.AlterField(
            model_name='personaje',
            name='anillo_principal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipado_anillo_principal', to='Characters.objeto'),
        ),
        migrations.AlterField(
            model_name='personaje',
            name='anillo_secundario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipado_anillo_secundario', to='Characters.objeto'),
        ),
        migrations.AlterField(
            model_name='personaje',
            name='botas',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipado_botas', to='Characters.objeto'),
        ),
        migrations.AlterField(
            model_name='personaje',
            name='cabeza',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipado_cabeza', to='Characters.objeto'),
        ),
        migrations.AlterField(
            model_name='personaje',
            name='cuello',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipado_cuello', to='Characters.objeto'),
        ),
        migrations.AlterField(
            model_name='personaje',
            name='guantes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipado_guantes', to='Characters.objeto'),
        ),
        migrations.AlterField(
            model_name='personaje',
            name='mano_principal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipado_mano_principal', to='Characters.objeto'),
        ),
        migrations.AlterField(
            model_name='personaje',
            name='mano_secundaria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipado_mano_secundaria', to='Characters.objeto'),
        ),
        migrations.AlterField(
            model_name='personaje',
            name='piernas',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipado_piernas', to='Characters.objeto'),
        ),
        migrations.AlterField(
            model_name='personaje',
            name='torso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipado_torso', to='Characters.objeto'),
        ),
    ]
