# Generated by Django 5.1.3 on 2024-11-19 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Characters', '0022_personaje_inventario_alter_inventario_heroe_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventarioobjeto',
            name='equipado',
            field=models.BooleanField(default=False),
        ),
    ]
