# Generated by Django 5.1.3 on 2024-11-19 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Characters', '0023_inventarioobjeto_equipado'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventarioobjeto',
            name='tipo',
            field=models.CharField(default='', editable=False, max_length=50),
        ),
    ]
